name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENCRYPTED_FILES_PASSPHRASE: ${{ secrets.ENCRYPTED_FILES_PASSPHRASE }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Decrypt google-services.json
        run: gpg --batch --decrypt --passphrase="$ENCRYPTED_FILES_PASSPHRASE" --output app/google-services.json app/google-services.json.gpg
      - name: Decrypt keystore
        run: gpg --batch --decrypt --passphrase="$ENCRYPTED_FILES_PASSPHRASE" --output app/virtually-challenging-keystore.jks app/virtually-challenging-keystore.jks.gpg
      - name: Decrypt keystore.properties
        run: gpg --batch --decrypt --passphrase="$ENCRYPTED_FILES_PASSPHRASE" --output app/keystore.properties app/keystore.properties.gpg
      - name: Build
        run: ./gradlew assemble
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: app/build/outputs/apk/**/*.apk